config/routes.rb
Rails.application.routes.draw do
  resources :geosets
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/geoset.rb
class Geoset < ApplicationRecord
  attr_accessor :err_message

  # Should be before has_one_attached to find file, because _after callbacks run in reverse order
  after_commit :file_upload, on: %i[create update], if: -> { geojson_file.attached? }
  after_commit :file_delete, if: -> { geojson_file.attached? }, unless: -> { @no_callback }
  before_save :json_parse, unless: -> { geojson_file.attached? }
  before_save :set_status

  with_options unless: -> { geojson_file.attached? } do |geoset|
    geoset.validates :geojson, presence: true
    geoset.validates :geojson, geojson: true
  end

  has_one_attached :geojson_file
  validates :geojson_file, file_type: ['application/geo+json']

  def raw_geojson
    geojson.to_json
  end

  private

  def json_parse
    self.geojson = JSON.parse(geojson)
  end

  def set_status
    @is_new = new_record?
  end

  def file_upload(*json)
    geojson_file.download { |f| json = JSON.parse(f) }
    # Using direct UPDATE SQL via update_column method to avoid infinite loop on callback
    update_column(:geojson, json)
  rescue StandardError => e
    logger.error "GeoJSON parse error: #{e.message}"
    self.err_message = 'Unable to upload file'
    # Cleaning up after upload error
    @is_new ? destroy : update_column(:geojson, JSON.parse(geojson))
  end

  def file_delete
    # Disabling callbacks because purge method updates the model
    @no_callback = true
    # Removing uploaded file
    geojson_file.purge
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/geosets_controller.rb
class GeosetsController < ApplicationController
  before_action :set_geoset, only: %i[show edit update destroy]
  after_action :err_message, only: %i[create update]

  # GET /geosets or /geosets.json
  def index
    @geosets = Geoset.all
  end

  # GET /geosets/1 or /geosets/1.json
  def show
  end

  # GET /geosets/new
  def new
    @geoset = Geoset.new
  end

  # GET /geosets/1/edit
  def edit
    # Setting hash object to string for form
    @geoset.geojson = @geoset.raw_geojson
  end

  # POST /geosets or /geosets.json
  def create
    @geoset = Geoset.new(geoset_params)

    respond_to do |format|
      if @geoset.save
        format.html { redirect_to @geoset, notice: "Geoset was successfully created." }
        format.json { render :show, status: :created, location: @geoset }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @geoset.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /geosets/1 or /geosets/1.json
  def update
    respond_to do |format|
      if @geoset.update(geoset_params)
        format.html { redirect_to @geoset, notice: "Geoset was successfully updated." }
        format.json { render :show, status: :ok, location: @geoset }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @geoset.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /geosets/1 or /geosets/1.json
  def destroy
    @geoset.destroy
    respond_to do |format|
      format.html { redirect_to geosets_url, notice: "Geoset was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_geoset
    @geoset = Geoset.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def geoset_params
    params.require(:geoset).permit(:name, :geojson, :geojson_file)
  end

  # Changing the notice message if any errors occured while parsing file
  def err_message
    return unless @geoset.err_message.present?

    flash[:notice] = nil
    flash[:alert] = @geoset.err_message
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/geosets_helper.rb
module GeosetsHelper
end

app/views/geosets/_form.html.erb
<%= form_with(model: geoset) do |form| %>
  <% if geoset.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(geoset.errors.count, "error") %> prohibited this geoset from being saved:</h2>

      <ul>
        <% geoset.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :geojson %>
    <%= form.text_field :geojson %>
  </div>

  <div class="field">
    <%= form.label :geojson_file %>
    <%= form.file_field :geojson_file %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/geosets/edit.html.erb
<h1>Editing Geoset</h1>

<%= render 'form', geoset: @geoset %>

<%= link_to 'Show', @geoset %> |
<%= link_to 'Back', geosets_path %>

app/views/geosets/index.html.erb
<% flash.each do |name, msg| %>
  <%= content_tag :p, msg, id: name %>
<% end %>

<h1>Geosets</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Geojson</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @geosets.each do |geoset| %>
      <tr>
        <td><%= geoset.name %></td>
        <td><%= geoset.geojson %></td>
        <td><%= link_to 'Show', geoset %></td>
        <td><%= link_to 'Edit', edit_geoset_path(geoset) %></td>
        <td><%= link_to 'Destroy', geoset, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Geoset', new_geoset_path %>

app/views/geosets/new.html.erb
<h1>New Geoset</h1>

<%= render 'form', geoset: @geoset %>

<%= link_to 'Back', geosets_path %>

app/views/geosets/show.html.erb
<% flash.each do |name, msg| %>
  <%= content_tag :p, msg, id: name %>
<% end %>

<p>
  <strong>Name:</strong>
  <%= @geoset.name %>
</p>

<p>
  <strong>Geojson:</strong>
  <%= @geoset.geojson %>
</p>

<%= link_to 'Edit', edit_geoset_path(@geoset) %> |
<%= link_to 'Back', geosets_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>